name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - uses: actions/checkout@v4

    - name: Fetch full clone
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile project
      id: make
      run: |
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: steps.make.outcome == 'success'
      with:
        name: artifacts
        path: |
          patcher.elf
          launcher.elf
          README.md
